AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Alexa Garage Door Opener - Lambda Functions

Globals:
  Function:
    Timeout: 10
    MemorySize: 128
    Runtime: provided.al2023
    Architectures:
      - x86_64
    Environment:
      Variables:
        PARTICLE_ACCESS_TOKEN: '{{resolve:ssm:/garage-door/particle-token:1}}'
        PARTICLE_DEVICE_ID: '{{resolve:ssm:/garage-door/device-id:1}}'

Parameters:
  AlexaSkillId:
    Type: String
    Description: Alexa Skill ID for skill invocation (leave empty to allow any skill during development)
    Default: ''

Conditions:
  HasAlexaSkillId: !Not [!Equals [!Ref AlexaSkillId, '']]

Resources:
  # Lambda function for Alexa Skill
  AlexaSkillFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      FunctionName: !Sub '${AWS::StackName}-alexa-skill'
      CodeUri: alexa-skill/
      Handler: bootstrap
      Description: Alexa skill handler for garage door control
      Policies:
        - Statement:
          - Sid: SSMParameterAccess
            Effect: Allow
            Action:
              - ssm:GetParameter
              - ssm:GetParameters
            Resource:
              - !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/garage-door/*'
      Events:
        AlexaSkill:
          Type: AlexaSkill
          Properties:
            SkillId: !If [HasAlexaSkillId, !Ref AlexaSkillId, !Ref AWS::NoValue]

  # CloudWatch Logs
  AlexaSkillLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${AlexaSkillFunction}'
      RetentionInDays: 7

Outputs:
  AlexaSkillFunctionArn:
    Description: ARN of the Alexa Skill Lambda Function
    Value: !GetAtt AlexaSkillFunction.Arn
    Export:
      Name: !Sub '${AWS::StackName}-AlexaSkillArn'

  AlexaSkillFunctionName:
    Description: Name of the Alexa Skill Lambda Function
    Value: !Ref AlexaSkillFunction
    Export:
      Name: !Sub '${AWS::StackName}-AlexaSkillName'

  Region:
    Description: AWS Region
    Value: !Ref AWS::Region

  StackName:
    Description: CloudFormation Stack Name
    Value: !Ref AWS::StackName
